version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
    volumes:
      - .:/var/www/html